### ISSUE TITLE
[BUG] About all zero monitoring and insecure protocols

### ISSUE THREAD

**Issue by hcwnbs** [openkruise/kruise#1916]
When I was using this software, I found some listening ports with all-zero values during the scanning process, such as 9876, 8080, 8090, and 8000. Moreover, the insecure TLS 1.0 and 1.1 protocols, as well as insecure cipher suites (for example, using RSA as the key exchange algorithm and cipher suites containing CBC symmetric cipher algorithms in the TLS protocol) are being used for port 9876. May I ask if there is any plan to address these issues?

![Image](https://github.com/user-attachments/assets/d4d8ac5c-1da6-4e90-8386-9113e101c8ae)

**Comment by furykerry** [comment]
it is related to the controller-runtime webhook setting, a possible fix can be refer to the [issue](https://github.com/kubernetes-sigs/controller-runtime/issues/2020)

**Comment by RohanMishra315** [comment]
Hey @furykerry Could I look into this ?

**Comment by RohanMishra315** [comment]
Got the idea how to solve this, but having problem where should the changes be made , @furykerry could you help me a bit .

**Comment by furykerry** [comment]
the webhook server initialization code is [here](https://github.com/openkruise/kruise/blob/master/main.go#L202)

**Comment by furykerry** [comment]
@hcwnbs actually there are two issues related
 
1. the use of tls 1.0 and 1.1
2. kruise webhook listen on all zero address 

#1 is already fixed in kruise 1.8 since we have upgraded the golang version to 1.22, in which , tls 1.2 is now the default minVersion for both server and client.

**Comment by hcwnbs** [comment]
> [@hcwnbs](https://github.com/hcwnbs) What version of kruise are you using?

I directly used the image, and the image version is 1.5.4.

**Comment by Crazy-Hopper** [comment]
Pardon, don't know how these bots work. Is this really "won't fix" ? Cause I still need a way to select cipher suites in order to fulfil PCI DSS requirements.

**Comment by furykerry** [comment]
it is still opened, but the previous assigned developer has closed the patch, and we have to find someone else to fix the issue

**Comment by Crazy-Hopper** [comment]
Hi! As per my understanding, please correct me if I'm wrong, this issue wasn't really resolved. If you agree, could you please reopen it ?
